name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    services:
      postgresql-db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: usersDb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 3: Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: docker build -t my-spring-boot-app .

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # Step 6: Tag and push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker tag my-spring-boot-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest

    # Cleanup: Remove the container after testing
    - name: Cleanup
      run: docker rm -f spring-boot-app || true
